### PR TITLE
Users can mark a listing as closed.

### PR DESCRIPTION
**Pull request by yoninachmany**
-Have a button or clickable text on resource page saying, "Is this resource no longer available?"
-Once user clicks, a window will open with optional text box to describe the situation. (Semantic-UI modal).
-Then user can submit.
-Once one or more users has reported a resource as unavailable, a message will display at the top of the resource page saying "[number of] users have reported that this resource is no longer available".
-This will be an expandable box. (Semantic-UI accordion maybe?)
screen shot 2015-12-06 at 2 35 23 pm
screen shot 2015-12-06 at 2 36 24 pm
screen shot 2015-12-06 at 2 36 30 pm
screen shot 2015-12-06 at 2 36 38 pm
screen shot 2015-12-06 at 2 36 52 pm
screen shot 2015-12-06 at 2 36 58 pm
screen shot 2015-12-06 at 2 37 02 pm

### CODE REVIEW

**Comment by yoninachmany** [comment]
NOTE: fixing bug for /createreview, /updatereview

**Comment by yoninachmany** [comment]
FIXED (i think)

**Comment by aharelick** [comment]
@yoninachmany, before I go through this and comment on specific lines can you please change `ClosedResourceExplanation` to `ClosedResourceDetails` or `ClosedResourceInfo`. Also, please make sure the html/jinja is properly indented (when you have a jinja `if` statement the html inside should be indented as well).

**Comment by yoninachmany** [comment]
looks like u got it

**Comment by aharelick** [comment]
@yoninachmany can you take a look at this code and give me the okay? Also pull the updates into your own branch and see if it's the functionality you're looking for.

**Pull request merged**
