### PR TITLE
Tag model - is_primary field

### PR DESCRIPTION
**Pull request by skylerwharton**
Added `is_primary` field to `Tag` model. These will be the `Tag`s that show up on the "Register" page (e.g., "Veteran", "Active Duty", etc.).

r @aharelick @anoshaminai

### CODE REVIEW

**Comment by anoshaminai** [comment]
Looks good to me! @aharelick can you take a look?

**Comment by aharelick** [comment]
what is this field?

**Comment by skylerwharton** [comment]
Read the PR description @aharelick

**Comment by aharelick** [comment]
k sorry, merge pls

**Pull request merged**
